#!/bin/sh

# nowplaying.sh – A simple, POSIX-compliant shell script to print the
# "Now Playing" status of a local Plex Server to stdout.
#
# Copyright 2022 Justin Teague <arcadellama@posteo.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the “Software”),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHE
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

PRGNAM="nowplaying.sh"
VERSION="0.9"

PLEX_HOST="${PLEX_HOST:-}"      # Plex server IP(s), separated by space
MAX_WIDTH="${MAX_WIDTH:-0}"     # Set the maximum width of print; 0=infinite
DOT_LEADER="${DOT_LEADER:-"."}" # Delimiter used for dot leader.
DL_AGENT="${DL_AGENT:-}"        # Either curl or wget
SKIP_CHECKS="${SKIP_CHECKS:-}"  # Skip dependency checks

## Functions

print_help() {
cat <<EOF

$PRGNAM, version $VERSION
a simple, POSIX-compliant script to print the "Now Playing" status
of a Plex server to stdout.

    Usage: '"$PRGNAM" -p localhost,127.0.0.1,192.168.1.1 -w 80 -d "." 

         --plex, -p   IP address(es) or domain name of Plex Server
                      separated by commas, no spaces. (Required)
        --width, -w   Maximum number of columns width.
                      Default=0, "infinite"
        --delim, -d   Dot leader for display. Default = "."
       
        --force, -f   Skip dependency checks.

EOF
}

dependency_check() {
    if [ ! -z "$DL_AGENT" ]; then
        true
    elif [ -x "$(command -v curl)" ]; then
        DL_AGENT="$(command -v curl)"
    elif [ ! -x "$(command -v wget)" ]; then
        DL_AGENT="$(command -v wget)"
    else
        printf "Error: neither curl nor wget found.\n"
        exit 1
    fi

    if [ -z "$SKIP_CHECKS" ]; then
        return 0
    fi

    # Let's make sure everything is here
    for __coreutil in tput grep cut sed; do
        if [ ! "$(command -v $__coreutil)" ]; then
            printf "Error: \"%s\" not found.\n" "$__coreutil"
            exit 1
        fi
    done

}


truncate_string() {
    __string="$1"
    __width="$2"
    __count="$(((${#__string} - __width) + 3))" # 3 additional for elipses

    while [ "$__count" -gt 0 ]; do
        __string="${__string%?}"
        __count="$((__count - 1))"
    done

    printf "%s..." "$__string"
}

print_delim() {
    __word="$1"
    __width="$2"
    __count=$((__width - __word))
    while [ "$__count" -gt 0 ]; do
        printf "%s" "$DOT_LEADER"
        __count=$((__count - 1))
    done
}

print_nowplaying() {
    __count="$1"
    __album="$2"
    __track="$3"
    __title="$4"
    __user="$5"
    __type="$6"
    __columns="$("$(command -v tput)" cols)"

    if [ "$MAX_WIDTH" -ne 0 ] && [ "$__columns" -gt "$MAX_WIDTH" ]; then
       __columns="$MAX_WIDTH"
    fi

    __col1="$((${#__count} + 1))"
    __col3="$((${#__user} + 1))"
    __col2="$((__columns - (__col3 +  __col1) - 4))"

    case "$__type" in
        episode)
              __title="${__album}: ${__track}"

              if [ "${#__title}" -gt "$__col2" ]; then

                  if [ "${#__album}" -gt "$__col2" ]; then
                  __album="$(truncate_string "$__album" "$__col2")"
                  fi

                  if [ "${#__track}" -gt "$__col2" ]; then
                  __track="$(truncate_string "$__track" "$__col2")"
                  fi

                  printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "$__count." "$__album" ""
                  printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "" "$__track $(print_delim ${#__track} ${__col2})" "$__user"
                else

              printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                  "$__count." "$__title $(print_delim ${#__title} ${__col2})" "$__user"
              fi
            ;;

          track)
              __title="${__album}: ${__track}"

              if [ "${#__title}" -gt "$__col2" ]; then

                  if [ "${#__album}" -gt "$__col2" ]; then
                  __album="$(truncate_string "$__album" "$__col2")"
                  fi

                  if [ "${#__track}" -gt "$__col2" ]; then
                  __track="$(truncate_string "$__track" "$__col2")"
                  fi

                  printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "$__count." "$__album" ""
                  printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "" "$__track $(print_delim ${#__track} ${__col2})" "$__user"
                else

              printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                  "$__count." "$__title $(print_delim ${#__title} ${__col2})" "$__user"

              fi
            ;;

          movie)
              if [ "${#__title}" -gt "$__col2" ]; then
                  __title="$(truncate_string "$__title" "$__col2")"
              fi
              printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                  "$__count." "$__title $(print_delim ${#__title} ${__col2})" "$__user"
            ;;
    esac
}

get_element() {
    echo "${2}" | grep -Eo "${1}=\"[a-zA-Z0-9?!&()#:;.,-_ ]*\"" | \
        cut -d '=' -f 2 | tr -d '"' | sed -e "s/\&\#39\;/'/g"
}

get_plexml() {
    oldIFS="$IFS"
    IFS=,
    set -- ${PLEX_HOST}
    for __host in "$@"; do
        case "$DL_AGENT" in
         *curl)
            "$DL_AGENT" -m 2 -s http://"$__host":32400/status/sessions
            if [ "$?" -eq 0 ]; then
                return "$?" 
            fi
            ;;
         *wget)
            "$DL_AGENT" -T 2 -qO - http://"$__host":32400/status/sessions
            if [ "$?" -eq 0 ]; then
                return "$?" 
            fi
            ;;
        esac
    done
    exit
}

parse_plexml() {
    __title=""
    __user=""
    __album=""
    __track=""
    __type=""
    #__series=""
    #__episode=""

    __count=0
    while IFS= read -r line; do
        case "$(get_element "type" "$line")" in
          episode)
                  __type="episode"
                  __album="$(get_element "grandparentTitle" "$line")"
                  __track="$(get_element "title" "$line")"
                  #__title="$(printf "%s:\n\t%s" "${__album}" "${__track}")"
                  continue ;;
          track)
              __type="track"
              __album="$(get_element "grandparentTitle" "$line")"
              __track="$(get_element "title" "$line")"
              #__title="$(printf "%s:\n\t%s" "${__album}" "${__track}")"
              continue ;;
          movie)
              __type="movie"
              __title="$(get_element "title" "$line")"
              continue ;;
        esac

        if echo "$line" | grep -q 'User id'; then
            __user="$(get_element "title" "$line")"
            if [ "$__count" -eq 0 ]; then
                printf "Now Playing on Plex:\n"
                __count="$((__count+1))"
            fi
            print_nowplaying "$__count" "$__album" "$__track" \
                "$__title" "$__user" "$__type"
            __count="$((__count+1))"

            continue
        fi

    done << EOF
    "$(get_plexml)"
EOF
}

main() {
    if [ "$#" -eq 0 ]; then
        print_help
        exit 0 
    fi

    while [ "$#" -gt 0 ]; do
        case "$1" in 
             --plex|-p)
                PLEX_HOST="$2"
                shift 2 ;;
            --width|-w)
                MAX_WIDTH="$2"
                shift 2 ;;
            --delim|-d)
                DOT_LEADER="$2"
                shift 2 ;;
            --force|-f)
                SKIP_CHECKS=1
                shift 1 ;;
             --help|-h)
                print_help
                exit 0 ;;
                     *)
	            printf "ERROR: \"%s\" is not a valid expression.\n" "$1"
	            printf "Try \"%s\" --help for help.\n" "$PRGNAM"
                exit 1 ;;
        esac
    done

    if dependency_check; then
        if parse_plexml; then
            printf "\n"
        fi
    fi
}

main "$@"
