#!/usr/bin/env sh

# nowplaying.sh – A simple, POSIX-compliant shell script to print the
# "Now Playing" status of a local Plex Server to stdout.
#
# Copyright 2022 Justin Teague <arcadellama@posteo.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the “Software”),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHE
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# shellcheck disable=2034

export LC_ALL=C

## Global Variables
prgnam="plex-nowplaying"
version="1.2.0"

## Optional command-line variables
plex_host="127.0.0.1"           # Plex server IP(s), separated by space
friendly_name="Plex"            # Default server name
max_width="0"                   # Set the maximum width of print; 0=infinite
dot_leader="."                  # Delimiter used for dot leader
color=""                        # Toggle color output--default is "auto"
verbose=""                      # Chatty version
dl_agent=""                     # Either curl, wget, or fetch
skip_checks=""                  # Skip dependency checks
plex_file=""                    # Optional XML for testing
plex_token=""                   # Auth token for Plex

## 
hw_transcode_symbol="•"         # Symbol to show hardware transcode
sw_transcode_symbol="◦"         # Symbol to show software transcode

## Text Color Definitions
black="\033[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
magenta="\033[35m"
cyan="\033[36m"
white="\033[37m"
 
## Text Effect Definitions
bold="\033[1m"
italic="\033[3m"
underline="\033[4m"

# Reset text colors/effects
treset="\033[m"

## Color Output Options
movie_color="$blue"
episode_color="$cyan"
song_color="$magenta"
transcode_color="$green"

## Functions
print_help() {
cat <<EOF

$prgnam, version $version
a simple, POSIX-compliant script to print the "Now Playing" status
of a Plex server to stdout.

Example: 'nowplaying -p 192.168.1.1 -w 80 -d "." -t <PLEX_AUTH_TOKEN>
         
        --plex, -p    IP address(es) or domain name of Plex Server
                      separated by commas, no spaces.
                      Default=127.0.0.1

        --token, -t   Plex Auth Token

        --width, -w   Maximum number of columns width.
                      Default=0, "infinite"

   --color <on|off>   Color setting. Default is to attempt to discover
                      your terminal settings and set accordingly.

         --help, -h   This screen

      --version, -v   Show version

      --curl <path>   Force curl as downloader.
                      (Path is optional.)

      --wget <path>   Force wget as downloader.
                      (Path is optional.)

     --fetch <path>   Force fetch as downloader.
                      (Path is optional.)
 
          --verbose   Print every error message.

             --file   Point to a XML file for debugging
EOF
}

no_server_error() {
    __ret="$1"
    if [ -n "$verbose" ]; then
        printf "Plex server not not found at %s. (Error code: %s)\n"\
            "$plex_host" "$__ret"
    fi
}

dependency_check() {
    if [ -n "$skip_checks" ]; then
        if [ -x "$dl_agent" ]; then
            return 0
        else
            printf "[%s]: Error. Cannot find a download agent.\n" "$prgnam"
            printf "Is curl, wget, or fetch installed?\n"
            return 1
        fi
    fi

    for __dla in curl wget fetch; do
        if [ -x "$(command -v "$__dla")" ]; then
        dl_agent="$(command -v "$__dla")"
        return 0
        fi
    done
    
    printf "Error: curl, wget, or fetch not found.\n"
    exit 1
}

color_check() {
    case "$color" in
        true|yes|on)
            return 0 ;;
       false|off|no)
            return 1 ;;
                  *)
            if [ -x "$(command -v tput)" ]; then
                if [ "$(tput colors)" ]; then
                    return 0
                fi
            fi
            return 1 ;;
    esac
}

set_color() { # Usage: set_color "string" "$color" "$effect" "$effect"
    __item="$1"
    __color="$2"
    __fx1="$3"
    __fx2="$4"
    if [ -n "$__fx2" ]; then
        printf "%b%b%b%s%b" "$__fx1" "$__fx2" "$__color" "$__item" "$treset"
        return
    elif [ -n "$__fx1" ]; then
        printf "%b%b%s%b" "$__fx1" "$__color" "$__item" "$treset"
        return
    elif [ -n "$__color" ]; then
        printf "%b%s%b" "$__color" "$__item" "$treset"
        return
    fi
    # Don't error-out if args aren't passed
    printf "%s" "$__item"
}

get_item() {
    __item="$1"
    __line="$2"
    set -f
    oldIFS=$IFS
    IFS='"'
    # shellcheck disable=2086
    set -- ${__line}
    while [ "$#" -gt 0 ]; do
        case "${1## }" in
            "$__item"=)
                printf "%s\n" "$2"
                shift 2 ;;
            *)
                shift ;;
        esac
    done
    IFS=$oldIFS
    set +f
}

truncate_string() {
    __string="$1"
    __width="$2"
    __count="$(((${#__string} - __width) + 3))" # 3 additional for elipses

    while [ "$__count" -gt 0 ]; do
        __string="${__string%?}"
        __count="$((__count - 1))"
    done

    printf "%s..." "$__string"
}

print_delim() {
    __word="$1"
    __width="$2"
    __count=$((__width - __word))
    while [ "$__count" -gt 0 ]; do
        printf "%s" "$dot_leader"
        __count=$((__count - 1))
    done
}

fix_apostrophe() {
    __input="$1"
    __oldIFS=$IFS
    IFS='&'
    # shellcheck disable=2086
    set -- ${__input}
    case "$2" in
        \#39\;*)
            IFS=$__oldIFS
            printf "%s'%s" "$1" "${2##\#39\;}"
            ;;
              *)
            printf "%s" "$1"
            ;;
    esac
}
	
server_url() {
    __host="$1"
    if [ -n "$plex_token" ]; then
        printf "http://%s:32400/?X-Plex-Token=%s" \
            "$__host" "$plex_token"
    else
        printf "http://%s:32400" \
            "$__host"
    fi
}

session_url() {
    __host="$1"
    if [ -n "$plex_token" ]; then
        printf "http://%s:32400/status/sessions?X-Plex-Token=%s" \
            "$__host" "$plex_token"
    else
        printf "http://%s:32400/status/sessions" \
            "$__host"
    fi
}

download_xml() {
    __url="$1"
    case "$dl_agent" in
        *curl)
            "$dl_agent" -m 2 -s "$__url"
             return "$?"
            ;;
         *wget)
            "$dl_agent" -T 2 -qO - "$__url"
            return "$?" 
            ;;
         *fetch)
            "$dl_agent" -T 2 -qO - "$__url"
            return "$?" 
            ;;
        esac
}

print_nowplaying() {
    __number="$1"
    __album="$(fix_apostrophe "$2")"
    __title="$(fix_apostrophe "$3")"
    __track="$__title"
    __user="$4"
    __type="$5"
    __transcode="$6"
    __columns=""

    # Set column width
    if [ "$(command -v tput)" ]; then
	__columns="$("$(command -v tput)" cols)"
        if [ "$max_width" -ne 0 ] && [ "$__columns" -gt "$max_width" ]; then
	        __columns="$max_width"
	    fi
    else
        if [ "$max_width" -ne 0 ]; then
            __columns="$max_width"
        else
            __columns="80"
        fi
    fi

    __col1="$((${#__count} + 1))"
    __col3="$((${#__user} + 1))"
    __col2="$((__columns - (__col3 + __col1) - 4))"

    # Set global color
    if color_check; then
        __transcode="$(set_color "$__transcode" "$transcode_color" "$bold")"
    fi

    case "$__type" in
        episode)
              # TV Episodes 
              __title="${__album}: ${__track}"

              # If it doesn't fit, spread over two lines
              if [ "${#__title}" -gt "$__col2" ]; then

                  if [ "${#__album}" -gt "$__col2" ]; then
                  __album="$(truncate_string "$__album" "$__col2")"
                  fi

                  if [ "${#__track}" -gt "$__col2" ]; then
                  __track="$(truncate_string "$__track" "$__col2")"
                  fi

                  __album="${__album}:"

                __output="$(printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "$__number." "$__album" "";  
                      printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "" "$__track $(print_delim ${#__track} ${__col2})" \
                      "$__user $__transcode")"
               else

                # Otherwise everything on one line
                __output="$(printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                  "$__number." \
                  "$__title $(print_delim ${#__title} ${__col2})" \
                  "$__user $__transcode")"

              fi
              if color_check; then
                __output="$(set_color "$__output" "$episode_color" "$bold")"
              fi
            ;;

          track)
              # Song tracks
              __title="${__album}: ${__track}"

              # If it doesn't fit, spread over two lines
              if [ "${#__title}" -gt "$__col2" ]; then

                  if [ "${#__album}" -gt "$__col2" ]; then
                  __album="$(truncate_string "$__album" "$__col2")"
                  fi

                  if [ "${#__track}" -gt "$__col2" ]; then
                  __track="$(truncate_string "$__track" "$__col2")"
                  fi

		          __album="${__album}:"

               # 2 lines
                __output="$(printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "$__number." "$__album" "";
                  printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "" "$__track $(print_delim ${#__track} ${__col2})" \
                      "$__user $__transcode")"
                else

                # All on one line
                __output="$(printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                      "$__number." \
                      "$__title $(print_delim ${#__title} ${__col2})" \
                      "$__user $__transcode")"

              fi
              if color_check; then
                __output="$(set_color "$__output" "$song_color" "$bold")"
              fi
            ;;

          movie)
              # Movies

              if [ "${#__title}" -gt "$__col2" ]; then
                  __title="$(truncate_string "$__title" "$__col2")"
              fi
              __output="$(printf "%${__col1}s %-${__col2}s%${__col3}s\n" \
                  "$__number." \
                  "$__title $(print_delim ${#__title} ${__col2})" \
                  "$__user $__transcode")"
              if color_check; then
                __output="$(set_color "$__output" "$movie_color" "$bold")"
              fi
            ;;
    esac
    # Final print to screen
    printf "%s\n" "$__output"
}

parse_server_xml() {
    # Input variable
    __server_xml="$1"
    while IFS= read -r line; do
        case "$line" in
            *MediaContainer*)
                friendly_name="$(get_item "friendlyName" "$line")"
                return
                ;;
        esac
    done << EOF
"$__server_xml"
EOF
}

parse_session_xml() {
    # Input variable
    __session_xml="$1"

    # Local variables
    __title=""
    __user=""
    __album=""
    __type=""
    __transcode=""

    __welcome_msg="Now Playing on $friendly_name: "
    __transcode_symbol=""
    __trans_type=""
    __count=0

    while IFS= read -r line; do
        case "$line" in
            ?Video*|?Track*)
                __type="$(get_item "type" "$line")"
                __album="$(get_item "grandparentTitle" "$line")"
                __title="$(get_item "title" "$line")"
                ;;

            *User\ id*)
                __user="$(get_item "title" "$line")"
                session="$((session+1))"
                ;;

            *TranscodeSession*)
                __trans_type=$(get_item "transcodeHwFullPipeline" "$line")
                if [ "$__trans_type" -eq 1 ]; then
                    __transcode_symbol="$hw_transcode_symbol"
                else
                    __transcode_symbol="$sw_transcode_symbol"
                fi
                __transcode="$__transcode_symbol"
                ;;

            */Video*|*/Track*)
                # Check if this is the first item
                if [ "$__count" -eq 0 ]; then
                        printf "\n"

                    if color_check; then
                        __welcome_msg="$(set_color \
                            "$__welcome_msg" "$white" "$italic" "$bold")"
                    fi
                        printf "%s\n" "$__welcome_msg"
                    __count="$((__count+1))"
                fi

                ###### Print to screen! #####
                print_nowplaying "$__count" "$__album" \
                    "$__title" "$__user" "$__type" "$__transcode"
                __count="$((__count+1))"
                ;;
            */MediaContainer*)
                # Check if end of xml file
                if [ "$session" -gt 0 ]; then
                    printf "\n"
                fi
                ;;
        esac
    done << EOF
"$__session_xml"
EOF

     if [ -n "$verbose" ] && [ "$__count" -eq 0 ]; then
         printf "Nothing playing on Plex.\n"
     fi
}

main() {
    while [ "$#" -gt 0 ]; do
        case "$1" in 
         --plex|-p)
                plex_host="$2"
                shift 2 ;;
        --token|-t)
                plex_token="$2"
                shift 2 ;;
        --width|-w)
                max_width="$2"
                shift 2 ;;
        --delim|-d)
		        printf "[%s]: --delim, -d is deprecated\n" "$prgnam"
                dot_leader="$2"
                shift 2 ;;
           --color)
                case "$2" in
                    on|off|auto|true|false|yes|no)
                        color="$2" 
                        shift 2 ;;
                    *)
                        color="on"
                        shift 1 ;;
                esac
                ;;
            --file)
                plex_file="$2"
                shift 2 ;;
        --force|-f)
		        printf "[%s]: --force is deprecated\n" "$prgnam"
                skip_checks=1
                shift 1 ;;
            --curl)
                case "$2" in
                    *curl)
                        if [ -x "$2" ]; then
                            dl_agent="$2"
                            shift 2 
                        else
                            printf "[%s]: Error. Cannot find %s.\n" \
                                "$prgnam" "$2"
                            exit 1
                        fi
                        ;;
                        *)
                        dl_agent="$(command -v curl)"
                        shift 1 ;;
                esac
                skip_checks=1 ;;

            --wget)
                case "$2" in
                    *wget)
                        if [ -x "$2" ]; then
                            dl_agent="$2"
                            shift 2 
                        else
                            printf "[%s]: Error. Cannot find %s.\n" \
                                "$prgnam" "$2"
                            exit 1
                        fi
                        ;;
                        *)
                        dl_agent="$(command -v wget)"
                        shift 1 ;;
                esac
                skip_checks=1 ;;
           --fetch)
                case "$2" in
                    *fetch)
                        if [ -x "$2" ]; then
                            dl_agent="$2"
                            shift 2 
                        else
                            printf "[%s]: Error. Cannot find %s.\n" \
                                "$prgnam" "$2"
                            exit 1
                        fi
                        ;;
                        *)
                        dl_agent="$(command -v fetch)"
                        shift 1 ;;
                esac
                skip_checks=1 ;;
         *verbose)
                verbose="1"
                shift 1 ;;
         *help|-h)
                print_help
                exit 0 ;;
      *version|-v)
                printf "%s: %s\n" "$prgnam" "$version"
                exit 0 ;;
                 *)
	            printf "[%s]: \"%s\" is not a valid expression.\n" \
		        "$prgnam" "$1"
	            printf "Try \"%s\" --help for help.\n" "$prgnam"
                exit 1 ;;
        esac
    done

    # Check for download agent
    dependency_check || exit 1

    # Debug mode check, simply cat the given xml file for testing
    if [ -n "$plex_file" ]; then
        parse_session_xml "$(cat "$plex_file")"
        return
    fi

    # Cycle through the given hostnames
    IFS=,
    # shellcheck disable=2086
    set -- ${plex_host}
    for __host in "$@"; do
        if __server_xml="$(download_xml "$(server_url "$__host")")"; then
            __session_xml="$(download_xml "$(session_url "$__host")")"
            parse_server_xml "$__server_xml"
            parse_session_xml "$__session_xml"
            return
        else
            __retval="$?"
        fi
    done
            no_server_error "$__retval"
            return "$__retval"
}
main "$@"
